version: '3'

services:
  mongodb:
    image: mongo:3.2
    command: mongod
    volumes:
      - ./mongodb:/data/db
    ports:
      - "27017:27017"

  redis:
    image: redis
    volumes:
      - ./redis:/data
    ports:
      - "6379:6379"

  elasticsearch:
    image: udata/elasticsearch:2.4.5
    volumes:
      - ./elasticsearch:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"

  udata:
    image: udata/udata
    links:
      - mongodb
      - redis
      - elasticsearch
    volumes:
      - ./fs:/udata/fs
      - ./udata-lecatalogue-theme/:/src/lecatalogue
      - ./config/udata.cfg:/udata/udata.cfg
      - ./uwsgi:/udata/uwsgi
    ports:
      - "80:7000"

