version: '2'

networks:
  default:
    external:
      name: ${NETWORK}

services:
  mongodb:
    image: mongo:3.2
    command: mongod
    volumes:
      - ./mongodb:/data/db

  redis:
    image: redis
    volumes:
      - ./redis:/data
    ports:
      - "6379:6379"

  elasticsearch:
    image: udata/elasticsearch:2.4.5
    volumes:
      - ./elasticsearch:/usr/share/elasticsearch/data

  udata:
    image: udata/udata
    links:
      - mongodb
      - redis
      - elasticsearch
    volumes:
      - ./fs:/udata/fs
      - ./udata-lecatalogue-theme/:/src/lecatalogue
      - ./config/udata.cfg:/udata/udata.cfg
      - ./uwsgi:/udata/uwsgi
    ports:
      - ${PORT}:7000

